# Generated by Django 6.0.6 on 2026-06-27 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)]),
        ),
    ]
