# Generated by Django 6.0.6 on 2026-07-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_like_unique_together_like_uniq_like_user_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='owner',
        ),
    ]
